### Create account - 요청 이름
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 10000
}

### Delete account - 요청 이름
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": 1000000002
}
