POST http://localhost:8080/transaction/use
Content-type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 20000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-type: application/json

{
  "transactionId": "9d64dbe163504610877d01c6f8b2de59",
  "accountNumber": "1000000002",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/5616f59fb3b146e7bbf3aeef38b65ebe